### ISSUE TITLE
Documentation needed: Suggested version numbering schema/process

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#356]
I have vdr_pi with ShipDriver Template 3.0.0,  building and working locally now.
I have set the version number to 1.3.12.1

```
set(PKG_NAME vdr_pi)
set(PKG_VERSION  1.3.12.1)
```

When I build it is labeled as 
`VDR-v1.3.12.0_msvc-10.0.19042-win32.tar.gz`

This is totally counter intuitive, or perhaps I have this plugin misconfigured?
I would like the fourth digit to show in order to allow me to be sure of the plugin I have imported, so that I know the one I am then installing is the one I want to test!    Also there are times I will want to use 4 digits to upload to Cloudsmith alpha or beta branch to provide a tarball for testing by someone else!

I would like to control myself, the use of just 3 digits for releases.  I do that normally and don't need to be overridden by the cmake program so that I am unsure of what I am testing!  etc, bitch, bit... b...  

Or perhaps I have something misconfigured?

BTW  I got a little deked by the use of plugin.cmake, but I think that is a good way to handle the particular setup for plugins.

**Comment by leamas** [comment]
PKG_VERSION is not used when you have tagged the commit, which I suspect you have. More exactly using a tag "v1.3.12.0".  You could whatever you want in the tag.

And, as I have tried to explain to no avail, having a detailed version in Plugin.cmake is just to create problems where you have to define the version in both Plugin.cmake and in the tag.

**Comment by rgleason** [comment]
Alec, I did not tag the commit.  In fact I have made no commit yet, I am just building and testing locally.

**Comment by rgleason** [comment]
Also, forgive me, but I have not reread the documentation lately, but promise to do so.

**Comment by leamas** [comment]
You could do what most people out there do (but not Dave): Plan your work.

So: say you plan to release 1.4.0 or so. You then is to set PKG_VERSION to 1.4.0, and keep it that way until it's finished.

During the development I first use untagged builds by importing them, needs no tag.

Later builds are tagged 1.4.0-beta1, 1.4.0-beta2 etc and could be tested in a wider audience, perhaps in the beta catalog. 

When releasing, I attach the v1.4.0 tag and all is done. I then update PKG_VERSION to, say, 1.4.1. Rinse and repeat.

**Comment by leamas** [comment]
> When I build it is labeled as VDR-v1.3.12.0_msvc-10.0.19042-win32.tar.gz

This version contains a 'v' prefix and have no buildinfo. I cannot understand this in any other way than that a tag is used..

Building from  a tree which is not clean (not committed)  is basically undefined, anything could happen, perhaps using the latest commit available.

**Comment by rgleason** [comment]
Yes, of course I plan my work.   I have been using what I call the 4th digit to distinguish local versions, so that when I import a built tarball, I can pick the right one to install and test.

I think you are suggesting that I should use "beta1", "beta2" in that 4th digit space, which I can certainly do. The difference is not much in terms of "planning"

I think the reason cmake is thinking that I have a "tagged" version, is because earlier I did make a tag for "v1.3.12.0" which I pushed up for a release.   So when I add in the 4th digit area  "1" or "beta1" instead of the "0", it thinks that it is a "tagged" version"?  That does not seem right to me.

So to avoid this "tag" problem , I am supposed to take the tagged released version that was pushed to "prod" and when starting changes,  first increment from "1.3.12.0"  to "1.3.13.<something>"  and use that for code changes, with tags such as  1.3.13.beta1,  1.3.13.beta2, 1.3.13.bet3, then to push and release using 1.3.13.0 with a tag v1.3.13.0    -- I guess I could do that, if that is what you want me to do.  It is a little different that how I have been working.

**Comment by rgleason** [comment]
I tried   `set(PKG_VERSION  1.3.13.beta1)`
and the build failed.

I tried   `set(PKG_VERSION  1.3.13.1)`
and got     VDR-v1.3.12.0_msvc-10.0.19042-win32.tar.gz

So this is a pseudo place to set the Version Number?
Where exactly do you want it set, and should I just leave this one blank?

**Comment by rgleason** [comment]
Note:  I am building locally using a batch file

**cd build
cmake -T v141_xp -G "Visual Studio 15 2017" ..
cmake --build . --target tarball --config RelWithDebInfo >output.txt**

**Comment by rgleason** [comment]
I just pushed it using  commit "1.3.13.1 + SD3.0.0"  without setting credentials to see what would happen

**Comment by rgleason** [comment]
So the results are a little puzzling. 
1. Git shows that everything "failed"   - probably because it did not deploy automatically to plugins?   - I haven't set that up.
2. https://github.com/rgleason/vdr_pi
2. Circleci show all the failures.
3.   https://app.circleci.com/pipelines/github/rgleason/vdr_pi?filter=all
2. Cloudsmith  alpha has all the builds with  a label of "1.3"   and a secondary of "1.3.13.1"  
3. https://cloudsmith.io/~opencpn/repos/vdr-alpha/packages/

**Comment by leamas** [comment]
>I  tried set(PKG_VERSION 1.3.13.beta1) and the build failed.

You still don't get it. If you plan to release 1.3.13 you set PKG_VERSION to 1.3.13, and let it stay that way. You will make multiple builds with the same  PKG_VERSION , but it doesn't matter, they all have a unique version including build number and git hash. 

When you want to create a beta you **tag**  a commit with 1.3.13-beta1. The version then becomes 1.3.13-beta1. Etc.

**Comment by leamas** [comment]
> sh: 1: ci/git-push.sh: Permission denied

This is because you copy files from one place to another in windows using cp, copy  or such. Windows cannot handle execute permissions, so when you copy a file it will be non-executable. The remedy is to use git to checkout files from the shipdriver repo rather than copying, either directly or using update-templates.

Now you are stuck with non-executable scripts. You need to fix the executable flag as described in https://stackoverflow.com/questions/21691202

**Comment by rgleason** [comment]
**1. Version numbers and multiple commits:**
"You still don't get it. If you plan to release 1.3.13 you set PKG_VERSION to 1.3.13, and let it stay that way. You will make multiple builds with the same PKG_VERSION , but it doesn't matter, they all have a unique version including build number and git hash."
Thanks, that makes the process clearer to me.

2. Git failure: sh: 1: ci/git-push.sh: Permission denied
"You copy files from one place to another in windows using cp, copy or such. Windows cannot handle execute permissions, so when you copy a file it will be non-executable." 
Thanks, I've had intermittant experience with this.I'll fix it and try to remember the problem.

**Comment by leamas** [comment]
Abusing the issue tracker with support requests is still a bad habit. Please close.

**Comment by rgleason** [comment]
Your schema for use of versioning is not explained anywhere that I know of.

**Comment by leamas** [comment]
Yes, but that scheme is not part of the templates,, it's just a hint how to use them in a simple and efficient way. If you want to use another scheme so fine, the templates basically allows anything.

That said, we should perhaps add a page on versioning to the docs. Versioning is one of those things which looks simple, but isn't. IIRC, the Fedora packaging manual has several pages on the subject.

This issue was as I see it filed because you  couldn't understand what happened  when you made build from a not committed version. That question is answered, you just cannot do that and expect a predictable result.

The rest is a discussion on how to handle the versioning. This is no bug, except *perhaps* in the documentation. So....

**Comment by rgleason** [comment]
Ok, this is now a relevant and current request for improvement of documentation.

**Comment by rgleason** [comment]
`, the templates basically allows anything.`

No, it does not. I did not support the most normal expected way to handle versioning.

**Comment by leamas** [comment]
Yup, it does, in the sense that a versioning scheme defines  the syntax used when defining new versions. That is the scheme.

Your problem is the *how* part, how to create versions. The templates are strongly biased to doing this by tagging commits rather than defining the version in the source.  But this does not limit what kind of versioning schemes which could be used, it's just about how they are implemented.

**Comment by rgleason** [comment]
I certainly agree with you about "how". Maybe it is a misunderstanding by me of the "how", and it likely is. For clarity it would be very good and useful to explain the "how" to use versioning "properly".  I will also follow that on testplugin.

**Comment by leamas** [comment]
New versioning page added to managed plugins docs: https://opencpn-manuals.github.io/main/AlternativeWorkflow/Versioning.html

**Comment by rgleason** [comment]
Thanks, looks good.
